version: '3.7'
services:
  app:
    container_name: full_app
    build: .
    ports: 
      - 8000:8000 
    restart: on-failure
    volumes:
      - api:/usr/src/app/
    depends_on:
      - faker-mysql   
    networks:
      - fullstack


  faker-mysql:
    image: mysql:5.7
    container_name: faker-mysql
    ports: 
      - 3306:3306
    environment: 
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
    volumes:
      - database_mysql:/var/lib/mysql
    networks:
      - fullstack

volumes:
  api:
  database_mysql:                  

# Networks to be created to facilitate communication between containers
networks:
  fullstack:
    driver: bridge